service: agent-study

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  architecture: x86_64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - bedrock:*
          Resource: "*"

plugins:
  - serverless-offline

custom:
  dotenv:
    path: .env
  pythonRequirements:
    dockerizePip: true
    layer: true
    # useDownloadCache: false
    # useStaticCache: false
    pipCmdExtraArgs:
      - --no-deps
    noDeploy:
      - boto3
      - botocore
      - jmespath
      - s3transfer

package:
  patterns:
    - "!**/*"
    - "src/**"
    - "requirements.txt"
  exclude:
    - __pycache__/**
    - "*.pyc"
    - "*.log"
    - boto3/**
    - botocore/**
    - jmespath/**
    - s3transfer/**

functions:
  chat:
    handler: src/lambda_handler.lambda_handler
    memorySize: 512
    timeout: 60
    url: true
    environment:
      LANGSMITH_API_KEY: ${env:LANGSMITH_API_KEY}
      TAVILY_API_KEY: ${env:TAVILY_API_KEY}
    layers:
      - Ref: PythonRequirementsLambdaLayer
